### ISSUE TITLE
missing prerequisite package "png"

### ISSUE THREAD

**Issue by BorisVSchmid** [caitiecollins/treeWAS#13]
On a fresh Rstudio (1.1.383), and with all non-base packages removed, installing treeWAS gives the following error.

> * preparing ‘treeWAS’:
> * checking DESCRIPTION meta-information ... OK
> * installing the package to build vignettes
> * creating vignettes ... ERROR
> Quitting from lines 111-115 (treeWAS_vignette.Rmd) 
> Error: processing vignette 'treeWAS_vignette.Rmd' failed with diagnostics:
> there is no package called 'png'
> Execution halted
> Installation failed: Command failed (1)

doing a _install.packages("png")_ prior to installing treeWAS fixes it.

**Comment by caitiecollins** [comment]
Hi Boris, 

Yes, the png package has thrown me a similar error in the past. I really thought I had fixed it by adding it to the Suggests in my Description file. It's only used for the vignettes, so technically that is where it should be. But I'm sorry it's still giving you this error. 

I've tried moving it to the Depends section now, so it should load no matter what. If you re-download and install the package, could you please let me know if that resolved the issue for you? 

Thanks for letting me know. 

Best wishes, 
Caitlin.

**Comment by BorisVSchmid** [comment]
Yeah, is resolved now. Thanks!

**Comment by caitiecollins** [comment]
That is wonderful news. Very glad to hear it. Thanks.

Cheers, 
CC
