### ISSUE TITLE
object treeWAS.out is missing when installing treeWAS

### ISSUE THREAD

**Issue by BorisVSchmid** [caitiecollins/treeWAS#14]
I am getting the following error when installing treeWAS

_install_github("caitiecollins/treeWAS/pkg", build_vignettes = TRUE)_

> * preparing ‘treeWAS’:
> * checking DESCRIPTION meta-information ... OK
> * installing the package to build vignettes
> * creating vignettes ... ERROR
> Quitting from lines 733-737 (treeWAS_vignette.Rmd) 
> Error: processing vignette 'treeWAS_vignette.Rmd' failed with diagnostics:
> object 'treeWAS.out' not found
> Execution halted
> Installation failed: Command failed (1)

Not using vignettes works.

_install_github("caitiecollins/treeWAS/pkg", build_vignettes = FALSE)_

Loading treeWAS after installing without vignettes gets me some library version warnings (see below), but otherwise the package seems to work fine

> > library(treeWAS)
> 
> Loading required package: adegenet
> Loading required package: ade4
> 
>    /// adegenet 2.1.0 is loaded ////////////
> 
>    > overview: '?adegenet'
>    > tutorials/doc/questions: 'adegenetWeb()' 
>    > bug reports/feature requests: adegenetIssues()
> 
> 
> Loading required package: ape
> Loading required package: Hmisc
> Loading required package: lattice
> Loading required package: survival
> 
> Attaching package: ‘survival’
> 
> The following object is masked from ‘package:adegenet’:
> 
>     strata
> 
> Loading required package: Formula
> Loading required package: ggplot2
> 
> Attaching package: ‘Hmisc’
> 
> The following object is masked from ‘package:ape’:
> 
>     zoom
> 
> The following objects are masked from ‘package:base’:
> 
>     format.pval, round.POSIXt, trunc.POSIXt, units
> 
> Warning messages:
> 1: package ‘adegenet’ was built under R version 3.4.2 
> 2: package ‘ape’ was built under R version 3.4.2 
> 3: replacing previous import ‘adegenet::AICc’ by ‘phangorn::AICc’ when loading ‘treeWAS’

**Comment by caitiecollins** [comment]
Hi again, 

Thank you for letting me know about this too. This one was my fault. I had renamed this vignette object to meet the wishes of a reviewer but I neglected to rename it somewhere else too. 

Now it's called treeWAS.example.out in all places and you should no longer get that error. Sorry about this one. 

Those package notice print-outs that you see are normal. They just load with the packages that treeWAS depends on, so you can ignore those ones. 

Again, thanks for the heads up. Very much appreciated. 

Best wishes, 
Caitlin.

**Comment by BorisVSchmid** [comment]
Did a fresh reinstall of R 3.4.2/Rstudio 1.1.383/gfortran-4.2.3.pkg on Mac, High Sierra.

build_vignettes = TRUE works fine now. Thanks!

**Comment by caitiecollins** [comment]
Excellent. Glad it's all running smoothly now. 

Don't hesitate to ask me if you run into any more issues. Always happy to help answer questions etc.. Or even to collaborate if you've ever got data that you'd like help analysing. 

Take care, 
CC
