### ISSUE TITLE
Memory limits, chunk size

### ISSUE THREAD

**Issue by caitiecollins** [caitiecollins/treeWAS#19]
Hi all, 

I got an e-mail asking about having to manually set the chunk.size argument each time when running treeWAS on large datasets that take up more memory than is available on your computer. 

I just thought I would post the answer here in case anyone else is suffering with a similar problem, as I realise it can be frustrating to try and guess an appropriate value for the chunk.size argument and then run out of memory anyway. 

So there is a new argument, **mem.lim**, which is designed to account for the amount of available memory on your PC and to override the chunk.size argument with a more appropriate value. 

**mem.lim = FALSE**  ----the default value, which will cause the new mem.lim argument to be ignored, allowing you to manually set the chunk.size argument as before. 

**mem.lim = _numeric value_** ----you can set mem.lim to any single numeric value to specify either the total amount of memory available on your machine, or some desired memory limit below the total available that you want to devote to treeWAS. This will prompt treeWAS to estimate***** the total amount of memory it will require (given your dataset size and n.snps.sim), and it will update the chunk.size value to ensure your computer doesn't run out of memory (over-riding any other chunk.size argument specified).

**mem.lim = TRUE** ----can be specified instead of a numeric value, and it will automatically check how much free memory is left on your computer. This is set up to work for Mac, Linux, and Windows systems. 

***** Please note: mem.lim is a new feature, and it does have to make an estimate of how much memory will be needed by treeWAS, which is not always an exact science. With that in mind, I would be grateful if you could please let me know if you find that the memory requirement being estimated is too far off in either direction, and I will try and make the estimate more precise over time with that feedback. 

Thanks very much. 

Best wishes, 
Caitlin.

**Comment by Carryxiaoqing** [comment]
Hi Caitlin,
When using treeWAS in R under Linux sever, I had a problem. My R script are as follows:
library(treeWAS)

test_snp <- read.table(file="snp.new.xls",row.names = 1, head = T)
test_snp <- as.matrix(test_snp)
n.snps.sim=ncol(snps) 
mem.lim=TRUE
test.tree <- read.tree(file ="tree.nwk")
test.phen <- read.csv(file = "Phenotype_data_1.csv",row.names = 1, head = F)
test.phen.1 <- test.phen$V2
names(test.phen.1) <- rownames(test.phen)
out <-treeWAS(snps = test_snp,phen = test.phen,tree=test.tree,seed=1)

But it occurs error like this "Some elements of tree$tip.label are absent from names(phen)." I had read all the issues that other users asked, but still haven't any idea. My tree file was constructed by fasttree with maximum likelihood method, which is unrooted and with BP values. All the isolate names of three files (snp file, phenotype file and tree file) are exactly the same.  There are 510 WGS isolates in our data (Could it be that too much data leads to such an error?) Thank you for your reply.

**Comment by cizydorczyk** [comment]
It looks like in your function call to treeWAS, you set phen=test.phen, but test.phen is not your phenotypes factor -- test.phen.1 is. So the function call should be:

`out <-treeWAS(snps = test_snp, phen = test.phen.1, tree=test.tree, seed=1)
`
replacing phen=test.phen with phen=test.phen.1

Also, have you tried running the checks suggested by the Wiki to ensure tip labels, names, etc. all match?

```
## Check that labels are present:
is.null(tree$tip.label)
is.null(rownames(snps))
is.null(names(phen))

## Cross-check labels with each other:
all(tree$tip.label %in% rownames(snps))
all(rownames(snps) %in% tree$tip.label)
all(tree$tip.label %in% names(phen))
all(names(phen) %in% tree$tip.label)
all(names(phen) %in% rownames(snps))
all(rownames(snps) %in% names(phen))
```

Hope that helps.

**Comment by Carryxiaoqing** [comment]
Hi cizydorczyk,
   Thank you for pointing out the mistakes in my script carefully. At present, my problem has been solved. Now, I have another question. Do you know how much data treeWAS software can run at most, take microbial strains or samples for example, how many strains or samples can run at most for microbial genome SNP.

Best,
Carryxiaoqing

**Comment by cizydorczyk** [comment]
I'm not sure there are any hard limits, but I've used it for ~200 strains with ~100K SNPs. I think the major limitation is memory -- treeWAS objects can get quite large, especially if you set n.snps.sim to something greater than its default value.

It should be able to handle your 510 isolates, provided you do not have TOO many SNPs...Best way to see is probably to try it out!

**Comment by Carryxiaoqing** [comment]
Hi cizydorczyk,
Thank you for your reply, I have tried my 510 isolates data (about 150k SNPs), and there was no problem with running treeWAS.

Best,
Carryxiaoqing
