### ISSUE TITLE
Significant p-value same as minimum p-value?

### ISSUE THREAD

**Issue by cizydorczyk** [caitiecollins/treeWAS#25]
Hello,

I have recently run treeWAS with a 277 sample dataset of 47,831 SNPs and obtain a single significant SNP based on the subsequent score. However, when I view the p-value of the SNP, it is identical to the minimum p-value reported by treeWAS below which a SNP will have a p-value of 0.

This has happened in two separate runs now, each simulating ~2 million SNPs each time (n.snps.sim=42*ncol(snps.dataset) and =45*ncol(snps.dataset)).

Furthermore, a Bonferroni threshold for the complete set of 47,831 SNPs using 3 tests is ~3.48E-7, whereas the minimum p-value reported by treeWAS is ~4.6E-7 in the above-mentioned runs, so I am not sure why it is being reported as significant at all. (as per issue #11 ) Note that I use a significance threshold of 0.05 and not the default 0.01.

I have tried to run treeWAS with ~3 million simulated SNPs but run into memory problems (only 64gb on my machine).

I was wondering if you could offer any insight as to what may be happening here, and whether it is possible to obtain an accurate p-value for the most significant SNP.

Any help is greatly appreciated.

Thank you,
Conrad Izydorczyk

**Comment by cizydorczyk** [comment]
I think I figured it out - a minimum p-value may be the same as the a SNPs p-value if only a single variant in the simulated dataset has a test statistic more extreme than that variant. Since a simulated variant at the very extreme of the distribution (the most extreme value) has no variants more extreme than it, its p-value would be reported as 0, and the p-value of the second-most extreme variant is what is reported as the "minimum p-value".

At least I think that's it.

**Comment by xavierdidelot** [comment]
Yes that sounds right. You could try increasing n.snps.sim to have more simulated SNPs and therefore more precise p-values, but you might still be left with some real SNP having a higher score than any of the simulated SNPs in which case the p-value is returned as zero.
