### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by LeonardosMageiros** [caitiecollins/treeWAS#26]
I am trying to install treeWAS and when I 
install_github("caitiecollins/treeWAS/pkg", build_vignettes = TRUE)
I get the following: 
Installation failed: error in running command

Any idea what I am doing wrong? 

Thank you in advance!

**Comment by xavierdidelot** [comment]
Well that error message isn't very explicit!
Maybe you could try:
install_github("caitiecollins/treeWAS/pkg", build_vignettes = F)
to see if the problem is with the vignettes. I think this will probably fail too though, in which case it would help if you could give a bit more context, for example which version of R you are using, etc.

**Comment by LeonardosMageiros** [comment]
Same error with the vignettes set to False. 
When I execute R.Version I get the following: 
$platform
[1] "x86_64-pc-linux-gnu"
$arch
[1] "x86_64"
$os
[1] "linux-gnu"
$system
[1] "x86_64, linux-gnu"
$status
[1] ""
$major
[1] "3"
$minor
[1] "4.4"
$year
[1] "2018"
$month
[1] "03"
$day
[1] "15"
$`svn rev`
[1] "74408"
$language
[1] "R"
$version.string
[1] "R version 3.4.4 (2018-03-15)"
$nickname
[1] "Someone to Lean On"

Also the commands 
install.packages("devtools", dep=TRUE)
library(devtools)
Where successfully executed. 

LEt me know if you need additional information.
Thank you very much in advance!

**Comment by xavierdidelot** [comment]
Is "Installation failed: error in running command" the only line of output you can see? Normally you should see something like this after your install command, and it would help to know how far it goes before the error happens:

Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo caitiecollins/treeWAS@master
from URL https://api.github.com/repos/caitiecollins/treeWAS/zipball/master
Installing treeWAS
etc...

**Comment by LeonardosMageiros** [comment]
Here is the full output after I run the command:
Downloading GitHub repo caitiecollins/treeWAS@master
from URL https://api.github.com/repos/caitiecollins/treeWAS/zipball/master
Installation failed: error in running command

**Comment by xavierdidelot** [comment]
Ok then I think for some reason it failed to download. Maybe you could do this manually instead. Click here to download the repository: https://api.github.com/repos/caitiecollins/treeWAS/zipball/master
This should download as a zip file called caitiecollins-treeWAS-c758578.zip 
You can unzip and install using:
```
unzip caitiecollins-treeWAS-c758578.zip
cd caitiecollins-treeWAS-c758578
R CMD INSTALL pkg
```

**Comment by LeonardosMageiros** [comment]
Thank you very much for all your help. 

I did the manual download. 
When I tried to install the pkg some dependencies were missing. 
After installing them "R CMD INSTALL pkg" worked fine. 
So now I run R, I execute library(treeWAS) successfully and then when I 
browseVignettes("treeWAS")
I get: 
No vignettes found by browseVignettes("treeWAS")

Nonetheless help(treeWAS) now gives me the help output, so I think it is installed correctly. 
Do you have any idea on how to fix the browseVignettes issue? 
Either way thank you very much for your help.

**Comment by xavierdidelot** [comment]
Thanks, do you remember which dependencies you had to install to get it to work?
The vignettes may not be visible via the browseVignettes tool, but you can see them here:
https://github.com/caitiecollins/treeWAS/tree/master/pkg/vignettes

**Comment by LeonardosMageiros** [comment]
Sorry for the delay. I remember that I installed ape and ggplot2 but there where others as well, that I can not recall. Apologies for that and thank you for your help.

**Comment by LeonardosMageiros** [comment]
Hi Xavier, 

I had to do the same procedure again as I still can not install treeWAS using the instructions.
Here are the dependencies that were missing when I executed "R CMD INSTALL pkg" in a new conda environment:
ERROR: dependencies ‘adegenet’, ‘ape’, ‘Hmisc’, ‘png’, ‘beeswarm’, ‘ggplot2’, ‘phangorn’, ‘phytools’, ‘pryr’, ‘scales’ are not available for package ‘treeWAS’. 

Installing these is solving the problem. 

Hope this is helpful. 

Best
Leonardos
