### ISSUE TITLE
about the recombination

### ISSUE THREAD

**Issue by zhaoxvwahaha** [caitiecollins/treeWAS#30]
Hi,

If my tree doesn't be constructed by recombination-aware approach, can treeWAS still consider this confounding effect in analysis.

Thanks in advance for your reply.

**Comment by xavierdidelot** [comment]
Yes you can use a standard phylogenetic tree, and treeWAS will still use the distribution of homoplasies against this tree to build up a picture of how much recombination should be corrected for. But we still recommend that treeWAS should be used alongside ClonalFrameML as described here https://github.com/caitiecollins/treeWAS/wiki/4.-Interpreting-Output
