### ISSUE TITLE
install error..

### ISSUE THREAD

**Issue by p931203** [caitiecollins/treeWAS#31]
```{r}
install.packages("devtools", dep=TRUE)
library(devtools)
install_github("caitiecollins/treeWAS", build_vignettes = TRUE)
library(treeWAS)

Then R says:
ERROR: lazy loading failed for package ‘treeWAS’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/treeWAS’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/treeWAS’
installation of package ‘/var/folders/7g/r76zj5p11tn812ys0v9p89200000gn/T//RtmpsCCHox/file3d41667052cc/treeWAS_1.0.tar.gz’ had non-zero exit status
> library(treeWAS)
Error in library(treeWAS) : there is no package called ‘treeWAS’

I don't know what can i do.. 
help me

**Comment by sekhwal** [comment]
Same error here .....

**Comment by xavierdidelot** [comment]
Could you please execute each of the four lines one at a time, and let us know if any error is returned when executing the first line, etc?

**Comment by sekhwal** [comment]
Hi,
The pipeline seems working, therefore I am trying to run following command
but showing error..

dna <- read.dna(file = "filename", format = "fasta")


Error in read.dna(file = "/home/science/TreeWas/uniprot.fasta", format
= "fasta"): could not find function "read.dna"

Traceback:

Also, please let me know what type of file is requirement to get the
results from TreeWas.

Thank you,

Manoj

**Comment by xavierdidelot** [comment]
Maybe you need to first load the R package ape from which the read.dna function comes from?
Try:
library(ape)

**Comment by sekhwal** [comment]
Hi,

It is treeWas still showing error with the following command.

tree <- read.nexus(file = "../TreeWas/tree.newick")

error########

Error in start:end: argument of length 0
Traceback:

1. read.nexus(file = "../TreeWas/tree.newick")

**Comment by xavierdidelot** [comment]
read.nexus is part of the ape package, not treeWAS, but if your file is in newick format you should use read.tree, also from ape.
