### ISSUE TITLE
Launching error TreeWas

### ISSUE THREAD

**Issue by sekhwal** [caitiecollins/treeWAS#35]
install.packages("devtools", dep=TRUE)
#################ERROR##################
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message in install.packages("devtools", dep = TRUE):
“'lib = "/usr/local/lib/R/site-library"' is not writable”
Error in install.packages("devtools", dep = TRUE): unable to install packages
Traceback:

1. install.packages("devtools", dep = TRUE)
2. stop("unable to install packages")
############################################################
install_github("caitiecollins/treeWAS", build_vignettes = TRUE)

Error in install_github("caitiecollins/treeWAS", build_vignettes = TRUE): could not find function "install_github"
Traceback:

**Comment by xavierdidelot** [comment]
This looks like an error when trying to install devtools, which is a prerequisite to installing treeWAS. It might help to specify where packages are installed, using the lib argument of the "install.packages function, see for example details at https://www.rdocumentation.org/packages/utils/versions/3.6.0/topics/install.packages

**Comment by sekhwal** [comment]
Hi,
I want to load my data by following commands to RUN treeWAS, it is showing
error.

## Load example data:
data(sequence.fasta)
data(phenotype)
data(seq.newick)


Warning message in data(sequence.fasta):
“data set ‘sequence.fasta’ not found”


Could you please suggest me steps to run treeWAS. I have a sequence
file, a tree file and a phenotype file.


Thank you,

**Comment by xavierdidelot** [comment]
See the read.FASTA function of the ape package to read a fasta file into R, and the read.tree function to read trees.
