### ISSUE TITLE
plot_phen

### ISSUE THREAD

**Issue by evezeyl** [caitiecollins/treeWAS#37]
Hi,
I am  trying your package: and using the testdata 
in your wiki for test data: 
plot_phen(tree, phen.nodes=phen.plot.col$all.nodes) - plots all in red.
Managed to make it work when transforming to logical.
I guess someting might not be functionning as you intended
All the Best
Eve

**Comment by martinastoycheva** [comment]
Hello, 


I just installed treeWAS and I have the same issue with the colours in the plot and I was wondering if it is fixed now or if you know whether there are compromised functionalities. 

Also, when the package is loaded the following warnings appear which may be related to the plotting function:

```
library(treeWAS)
Loading required package: adegenet
Loading required package: ade4
Registered S3 method overwritten by 'spdep':
  method   from
  plot.mst ape 

   /// adegenet 2.1.3 is loaded ////////////

   > overview: '?adegenet'
   > tutorials/doc/questions: 'adegenetWeb()' 
   > bug reports/feature requests: adegenetIssues()


Loading required package: ape
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
```

**Comment by hollygene** [comment]
This is happening to me too, good to know converting it to logical works.
