### ISSUE TITLE
Axis problem

### ISSUE THREAD

**Issue by Nerdobyte** [caitiecollins/treeWAS#38]
Hi,
I was wondering if you could help me? So when I run the following treeWAS command I keep getting the "Error in axis" comment below:

```
> out <- treeWAS(snps = geney,
+                phen = pheny,
+                na.rm=TRUE,
+                tree = "BIONJ",
+                seed = 1)
Error in axis(side = side, at = x, labels = lab, ...) : 
  no locations are finite
```

The following is a short description of my data:

```
> class(geney)
[1] "matrix"
> str(geney)
 num [1:27, 1:62] NA NA NA NA NA 0 NA NA NA NA ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:27] "FR3883.vcf" "FR3977.vcf" "FR4887.vcf" "FR4928.vcf" ...
  ..$ : chr [1:62] "X1000756.G" "X1000756.t" "X1001126.g" "X1001126.T" ...
> class(pheny)
[1] "factor"
> str(pheny)
 Factor w/ 2 levels "A","B": 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "names")= chr [1:27] "FR4887.vcf" "FR4928.vcf" "FR4930.vcf" "FR5128.vcf" ...
```

Any feedback would be greatly appreciated. 
Cheers =)

**Comment by xavierdidelot** [comment]
Maybe you could try to run treeWAS without plotting anything using the following arguments:
plot.tree = F, plot.manhattan = F, plot.null.dist = F,  plot.dist = F
This way you will at least get an output which should help you diagnose the problem.
