### ISSUE TITLE
Error in generating Manhattan plot

### ISSUE THREAD

**Issue by JialunWu** [caitiecollins/treeWAS#39]
Hi I've been trying to test treeWAS on a set of 62 bacterial genomes, although treeWAS seems to work fine, I always have this error output when using manhattan.plot function regardless using output from terminal/simultaneous/subsequent, and the graph it generates has been attached

![Rplot](https://user-images.githubusercontent.com/52544917/60683209-7a8b3980-9e8e-11e9-95ae-21a33118f4ef.png)

> manhattan.plot(pHout$subsequent$p.vals)
Error in xy.coords(x, y) : 'x' and 'y' lengths differ
In addition: Warning message:
In max(sig.thresh) : no non-missing arguments to max; returning -Inf

Looking forward to hear from you. Thanks!

**Comment by JialunWu** [comment]
Hi I've just found out the problem. I just have to scroll back to previous plots generated in RStudio, as you suggested in one of your previous answers! Sorry if this has bothered you! I'm just quiet new to R.

Thanks a lot! Great GWAS program!

**Comment by xavierdidelot** [comment]
Thanks, I'm really glad you solved it!
