### ISSUE TITLE
How does the tool calculate the p-value?

### ISSUE THREAD

**Issue by Owen-haha** [caitiecollins/treeWAS#5]
Fantastic tool to be tried! Before applying it to my dataset, I want to know more about it. 
It is obvious that three different scores have been calculated by the tool. But there is little about how does the tool obtain p-values for these three scores. I referred to the paper and found little about it. Can anyone kindly explain it explicitly? Thanks!

**Comment by caitiecollins** [comment]
Hi, 

Thanks very much for your interest! 

The p-values are calculated in a straightforward count-based manner and in the same way for all scores. We draw these values with reference to the null distribution (the distribution of association score values for the simulated null genetic data) and calculate the p-value as the proportion of values above a given value. 

So, for a given association score value in the real dataset, _X_, the p-value would be the number of association score values in the null distribution that exceed _X_, divided by the total number of values in the null distribution (ie. the number of simulated sites, _Nsim_). For any significant association scores that fall beyond the upper tail of the null distribution, we can only say that their p-value is lower than the smallest available p-value, so these are given as "_p_ < 1/_Nsim_". 

Hope that helps. Please let me know if I can offer any further clarification.

Best, 
CC

**Comment by Owen-haha** [comment]
Thanks so much! It's clear to me now.
