### ISSUE TITLE
Too few positive probabilities Error

### ISSUE THREAD

**Issue by amzurita** [caitiecollins/treeWAS#54]
Hi!

I have been trying to use treeWAS to analyze my own dataset of variant calls plus a binary resistance phenotype (Resistant/Sensitive). Without providing a tree or ancestral reconstruction, I keep running into the following error:

```R
out <- treeWAS(snps = t_snps_m,
+                phen = phen_m,
+                seed = 1)
If tree is not a phylo object, please specify one of the following reconstruction methods:
          'NJ', 'BIONJ', 'parsimony', 'NJ*', 'BIONJ*'. Choosing 'BIONJ' by default.
Setting 5 negative branch lengths to zero.
Error in sample.int(length(x), size, replace, prob) : 
  too few positive probabilities
In addition: Warning message:
In if (class(dna) != "DNAbin") { :
  the condition has length > 1 and only the first element will be used
```

Do you know what the issue is? 

I have tried a few things:
- There is a specific subset of 123 samples (out of the 307 that I am using) where treeWAS runs and doesn't encounter this issue. However, when running with the remaining 184, the exact same error happens.
- I have tried running the tree building function and it ran properly, providing a tree that looked correct:
```R
tree <- tree.reconstruct(t_snps_m,
                         method = 'BIONJ',
                         dist.dna.model = "JC69", 
                         plot = TRUE)
```

- I tried running the ASR reconstruction independently and it also ran without issues:
```
phen.rec <- asr(var=phen_mica, tree=tree, type="ML", method="discrete")
```

Thank you a lot,
Aina

**Comment by muxiaoxin51** [comment]
I guess in tree="NJ" condition, the following makes 'if (class(dna) != "DNAbin")' error.
In function treeWAS() ,
tree <- tree.reconstruct(dna=snps, method = tree, dist.dna.model = dist.dna.model, 
                             plot = FALSE), cause this 'if (class(dna) != "DNAbin")' error.
and in function tree.reconstruct(), class(dna) return c("matrix","array") with R version 4.2.1, while 'if (class(dna) != "DNAbin")' need class(dna) return "matrix" only. But I don't know how to set class return "matrix" only.

**Comment by caitiecollins** [comment]
Thank you for pointing this out. I've just pushed a small change that should fix this in future, if you reinstall treeWAS. But please let me know if you run into any other problems. 

Best, 
Caitlin.
