### ISSUE TITLE
Just a question: Can you recommend method for SNPs matrix generation?

### ISSUE THREAD

**Issue by martinastoycheva** [caitiecollins/treeWAS#57]
Hello,

I have ran treeWAS with a gene presence/absence matrix and it works fine so I wanted to try the SNPs as well but I am confused  about the format that treeWAS requires and I was wondering if you can clarify a few things.

1. Usually softwares generate vcf files when snp calling is performed so is there an easy way of converting a vcf file to the binary SNP matrix required by treeWAS?
2. Do you recommend getting the SNPs from the alignment of the multiple genomes or by performing variant calling with something like Freebayes and then getting a consensus? 
3. Is there a pipeline or a recommended method that you tend to use in order to generate the SNPs matrix suitable for treeWAS?

Thank you for the help!
Martina

**Comment by hsinjou0714** [comment]
Hi Martina,
I am also having this issue too. Have you found out a solution on converting vcf to matrix or a tool that may be good for treeWAS? 
Thank you,
Christine

**Comment by uyghbo** [comment]
Hi Martina,
I am also having this issue too. what did the ‘0’, '1', 'NA', mean in treeWAS data(snps)?
Thanks
