### ISSUE TITLE
Trouble with trees

### ISSUE THREAD

**Issue by d-j-e** [caitiecollins/treeWAS#6]
I have been testing some data sets and have trouble with the trees - got rather non-informative error messages about the 'expectations' of the tree. Could you please include some notes on the expectations and limits of the tree (apart from all the tip labels being in the other data sets i.e does it need to be unrooted? Should I remove the outgroup before using in treeWAS etc. )?

btw, here is the error message...
This simulation procedure expects to find the root node/first internal node (ie. n.terminal+1) in either the FIRST or LAST row of tree$edge[,1], once the tree has been reordered to be in 'pruningwise' configuration. This is NOT the case with your tree. Please check.

thanks in advance,
David Edwards

**Comment by caitiecollins** [comment]
Hello, 

Yes, I've added a little more documentation to the treeWAS function and vignette within the package now, although I apologise if that was a little unclear. I'll also update the documentation on GitHub shortly, although this has not yet been done. 

Requirements for the tree are that it should only contain terminal nodes corresponding to the individuals under analysis and internal nodes that are their ancestors. Any additional individuals, including the outgroup, if not under analysis should be removed prior to running. The tree can be either rooted or unrooted. 

The admittedly confusing error message you received is actually still relevant as well for the simulation of the null genetic data. Once you have met the requirements above, would you be able to take a look at tree$edge and let me know if the N.terminal+1th individual (ie. if you have 10 terminal nodes, the 11th node) is in either the first or last row of the first column of tree$edge? 

Generally speaking, I believe this should be the case, but there may be something I haven't thought of. Anyway, if it's not the case, could you please paste tree$edge into a message back to me (or send me the tree if it's possible) and I will find a way to accommodate your tree structure. 

Thanks and all the best,
Caitlin.

**Comment by d-j-e** [comment]
[RAxML_bestTree.allTBm_99cons_1807.txt](https://github.com/caitiecollins/treeWAS/files/1103954/RAxML_bestTree.allTBm_99cons_1807.txt)

Here is one tree that creates that error message: warning, its big!

**Comment by caitiecollins** [comment]
Hi, 

Thanks for sending me that. I've implemented a fix that I believe should solve the problem. 

Please let me know if it works for you now?

Cheers, 
Caitlin.

**Comment by d-j-e** [comment]
Yes, that does indeed work now... Thank you

**Comment by caitiecollins** [comment]
Excellent. Thanks for letting me know! 

Best, 
CC
