### ISSUE TITLE
Testing burden score binary variants association 

### ISSUE THREAD

**Issue by DorothyTamYiLing** [caitiecollins/treeWAS#61]
Hi Caitie,

First of all, thanks for writing treewas, it has been really useful in my work. 

I am trying to do an amino acid burden score GWAS (for any codon, retainment of reference amino acid is coded as 0 and change to any alternative amino acid is coded as 1), as also gene burden score GWAS (for any gene, code as 1 in the presence of at least one gene inactivating allele, and code as 0 otherwise). It is still binary genotype and I am wondering if this would be appropriate to use the 3 association tests implemented in treewas? The tree I used was generated using core genome SNP information.

Thanks,
Dorothy

**Comment by caitiecollins** [comment]
No problem!
I should note so no one reading this gets confused, that I am just using the term "one-sided" to describe why you could lose some statistical power in a GWAS analysis like this, not that this would be a formally one-sided association test or to imply any change to the GWAS procedure.
