### ISSUE TITLE
Error in ncol(snps.ori) : object 'snps.ori' not found

### ISSUE THREAD

**Issue by Tonny-zhou** [caitiecollins/treeWAS#65]
Dear author,

Thank you very much for this great gwas tool! I am sorry for bothering you... When I was running the sample data, I encountered an error. Can you help me solve it ?

```
>data(snps)
>data(phen)
>data(tree)
>treeWAS(snps = snps,phen = phen,tree = tree,seed = 1)

1414 snps columns are over 50% NAs.
            You may want to consider removing these columns as they are unlikely to be significant
            and can generate inappropriate inferences during ancestral state reconstruction.Note: Updating n.snps.sim to match 10x the number of real loci after data cleaning.
                Input: 200030 -->
                Updated: 184510
[1] "treeWAS snps sim done @ 2022-11-08 18:27:18"
Error in ncol(snps.ori) : object 'snps.ori' not found
```

**Comment by myoungblom** [comment]
I am having the same error (not with sample data but real data). Hoping it will be a simple fix! :)

**Comment by caitiecollins** [comment]
Oh dear, must be a bug! I'll try to get it fixed by tomorrow.

**Comment by caitiecollins** [comment]
Thanks for your patience. 
The error should be fixed now! 
Please let me know how it goes. 

#bugHaiku

**Comment by Estellaknight** [comment]
> Thanks for your patience. The error should be fixed now! Please let me know how it goes.
> 
> #bugHaiku

I re-installed the package after the bug fixed, but still got the same error messages with the sample data. Is there any suggestion for it? Many thx!

**Comment by caitiecollins** [comment]
The snps.ori error or the other warning messages or both?

**Comment by Estellaknight** [comment]
> The snps.ori error or the other warning messages or both?

Thx for the quick reply! It was the snps.ori error. Exactly like this one:"Error in ncol(snps.ori) : object 'snps.ori' not found".

**Comment by ruutmdlv** [comment]
I found the same error! ("Error in ncol(snps.ori) : object 'snps.ori' not found"). I also reinstalled and continue having the same problem.

**Comment by caitiecollins** [comment]
I'll take another look at it today. Thanks for letting me know.

**Comment by caitiecollins** [comment]
I'm struggling to reproduce the snps.ori error with the most recent version installed. 
Could anyone still getting the snps.ori error please run these lines and tell me what it returns: 

`pi <- package_info()`
`pi[pi$package=="treeWAS",]`

Thank you.

**Comment by ruutmdlv** [comment]
Restarted my pc and now works great. Thanks a lot for the fast fixing!

**Comment by caitiecollins** [comment]
Huzzah! Glad to hear it.
