### ISSUE TITLE
Error in .Call

### ISSUE THREAD

**Issue by ViroMSu** [caitiecollins/treeWAS#7]
Have tried running treeWAS but coming across this error. 

Error in .Call("FITCH", data[, tree$tip.label], as.integer(nr), as.integer(node),  : 
  "FITCH" not resolved from current namespace (phangorn)

Traceback:
4. fit.fitch(tree, data, site)
3. fitch.phangorn(tree, snps.phyDat, site = "site")
2. get.fitch.n.mts(snps = snps, tree = tree)
1. treeWAS(snps = t_matrix2, phen = dtox_1, tree = parsnp_tree2, n.subs = NULL, n.snps.sim = ncol(snps) * 10, chunk.size = ncol(snps), test = c("terminal", "simultaneous", "subsequent"), snps.reconstruction = "parsimony", snps.sim.reconstruction = "parsimony", phen.reconstruction = "parsimony", na.rm = TRUE,  p.value = 0.01,  p.value.correct = "bonf",  p.value.by = "count",            dist.dna.model = "JC69",  plot.tree = FALSE,  plot.manhattan = TRUE, plot.null.dist = TRUE,               plot.dist = FALSE,  snps.assoc = NULL,  filename.plot = NULL, seed = 1)

Seems to also throw this error with test data, so I suspect it has something to do with package loading. Phangorn version 2.2.0. R version 3.4.0
Any insight appreciated,
Michelle Su

**Comment by ViroMSu** [comment]
Fixed by restarting R and reloading packages.

**Comment by caitiecollins** [comment]
Hi, 

I'm glad you were able to resolve the problem. 

Would you be able to reproduce the problem by any chance? It would be useful for me to know what factors might be causing this error. 

In any case, may I ask that if you run into the problem again in the future, could you please let me know and include any facts (other packages loaded, etc.) that you think may be relevant?

Thanks very much, 
Caitlin.
